#!/bin/bash 
#PBS -l walltime=12:00:00 
#PBS -l mem=190GB 
#PBS -l ncpus=48
#PBS -l jobfs=100GB 
#PBS -l storage=gdata/dk92+gdata/rv74+gdata/ob53+scratch/er8
#PBS -l other=hyperthread 
#PBS -q normal
#PBS -P v46
#PBS -o /home/548/cd3022/repos/CPDiT/outputs/logs/prime_cache.log
#PBS -j oe



# Set up directories
cd /home/548/cd3022/repos/CPDiT

# PBS Job Script for training CPDiT on HPC cluster
source hpc_setup.sh

bash scripts/prime_cache.sh