#!/bin/bash 
#PBS -l walltime=12:00:00 
#PBS -l mem=1024GB 
#PBS -l ncpus=48
#PBS -l ngpus=4
#PBS -l jobfs=1024GB 
#PBS -l storage=gdata/dk92+gdat/rv74+gdata/ob53+scratch/er8
#PBS -l other=hyperthread 
#PBS -q gpuhopper
#PBS -P v46
#PBS -o /home/548/cd3022/repos/CPDiT/outputs/logs/training.log
#PBS -j oe



# Set up directories
cd /home/548/cd3022/repos/CPDiT

# PBS Job Script for training CPDiT on HPC cluster
source hpc_setup.sh


# Run training
echo "Starting CPDiT training on GPU..."

# To resume, append:
#   --resume /scratch/er8/cd3022/CPDiT/testing_checkpoints/best_model.pt
torchrun --nproc_per_node=4 -m src.training.train \
    --config configs/train_config.yaml

echo "Training job completed!"
