#!/bin/bash 
#PBS -l walltime=48:00:00 
#PBS -l mem=1024GB 
#PBS -l ncpus=48
#PBS -l ngpus=4
#PBS -l jobfs=100GB 
#PBS -l storage=gdata/dk92+scratch/er8
#PBS -l other=hyperthread 
#PBS -q gpuhopper
#PBS -P v46
#PBS -o /home/548/cd3022/repos/CPDiT/outputs/logs/training_stage2.log
#PBS -j oe 



# Set up directories
cd /home/548/cd3022/repos/CPDiT

# PBS Job Script for training CPDiT on HPC cluster
source hpc_setup.sh


# Run training
echo "Starting CPDiT training on GPU..."
torchrun --nproc_per_node=4 -m src_testing.training.train \
    --config configs/experimental_config.yaml

echo "Training job completed!"
